# Generated by Django 3.2 on 2023-05-06 05:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='readers',
            field=models.ManyToManyField(blank=True, related_name='read_chats', to=settings.AUTH_USER_MODEL),
        ),
    ]
