# Generated by Django 3.2 on 2023-07-19 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_chat_readers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
