# Generated by Django 3.2 on 2023-04-30 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coder', '0002_questions_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='points',
            field=models.FloatField(default=3, verbose_name='Points'),
        ),
    ]
