# Generated by Django 3.2 on 2023-04-30 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Coder', '0003_questions_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('pending', 'Pending'), ('closed', 'Closed')], default='open', max_length=10),
        ),
        migrations.CreateModel(
            name='PlayerScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner_answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Coder.answers', verbose_name='winner_answer')),
            ],
        ),
    ]
