# Generated by Django 3.2 on 2023-05-01 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Coder', '0004_auto_20230430_0046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Event Name')),
                ('date', models.DateField(verbose_name='Event Date')),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionsRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Rule Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('points', models.FloatField(verbose_name='Points')),
                ('bonus_exact_answer', models.FloatField(verbose_name='Bonus Exact Answer')),
                ('allows_draw', models.BooleanField(default=True, verbose_name='Allows Draw')),
                ('allows_wildcard', models.BooleanField(default=False, verbose_name='Allows Wildcard')),
                ('points_draw', models.FloatField(verbose_name='Points Draw')),
            ],
        ),
        migrations.RemoveField(
            model_name='questions',
            name='points',
        ),
        migrations.AddField(
            model_name='questions',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Coder.event', verbose_name='Event'),
        ),
        migrations.AddField(
            model_name='questions',
            name='question_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Coder.questionsrules', verbose_name='Question Rule'),
        ),
    ]
