# Generated by Django 3.2 on 2023-05-01 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coder', '0005_auto_20230501_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='result',
            field=models.CharField(choices=[('undetermined', 'Undetermined'), ('determined', 'Determined')], default='undetermined', max_length=20),
        ),
        migrations.AlterField(
            model_name='questions',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10),
        ),
    ]
