# Generated by Django 3.2 on 2023-05-01 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coder', '0007_event_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerscore',
            name='points',
            field=models.FloatField(default=0, verbose_name='Points'),
        ),
    ]
