# Generated by Django 3.2 on 2023-05-06 04:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coder', '0008_playerscore_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='date_birth',
            field=models.DateField(blank=True, default=datetime.date(2000, 1, 1), null=True, verbose_name='Birth'),
        ),
    ]
