# Generated by Django 3.2 on 2023-07-19 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coder', '0009_alter_players_date_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsrules',
            name='last_position_penalty',
            field=models.BooleanField(default=True, verbose_name='Last Position Penalty'),
        ),
        migrations.AddField(
            model_name='questionsrules',
            name='points_last_position_penalty',
            field=models.FloatField(default=0, verbose_name='Points Last Position Penalty'),
        ),
    ]
