# Generated by Django 3.2 on 2023-07-20 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coder', '0010_auto_20230719_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsrules',
            name='label_last_position',
            field=models.TextField(default='Penalizado', verbose_name='Label Last Position'),
        ),
    ]
